export type AriaLabel =
	| string
	| 'Get Started'
	| 'Learn more'
	| 'Close'
	| 'Submit'
	| 'Help'
	| 'Menu'
	| 'Search'
	| 'Next'
	| 'Previous'
	| 'Play'
	| 'Pause'
	| 'Volume Up'
	| 'Volume Down'
	| 'Mute'
	| 'Expand'
	| 'Collapse'
	| 'Delete'
	| 'Edit'
	| 'Add'
	| 'Save'
	| 'Cancel'
	| 'Download'
	| 'Upload'
	| 'Refresh'
	| 'Info'
	| 'Warning'
	| 'Error'
	| 'Success'
	| 'Home'
	| 'Settings'
	| 'Profile'
	| 'More'
	| 'Close Menu'
	| 'Open Menu'
	| 'Toggle'
	| 'Read More'
	| 'Read Less'
	| 'Email'
	| 'Phone'
	| 'Calendar'
	| 'Share'
	| 'Print'
	| 'Back'
	| 'Forward'
	| 'Top'
	| 'Bottom'
	| 'Help Info'
	| 'Language'
	| 'Accessibility'
	| 'Notifications'
	| 'User'
	| 'Location'
	| 'Lock'
	| 'Unlock'
	| 'Search Results'
	| 'Sort Ascending'
	| 'Sort Descending'
	| 'Filter'
	| 'Select'
	| 'Deselect'
	| 'Favorite'
	| 'Unfavorite'
	| 'Star'
	| 'Unstar'
	| 'Tag'
	| 'Untag'
	| 'Heart'
	| 'Unheart'
	| 'Like'
	| 'Unlike'
	| 'View'
	| 'Edit Profile'
	| 'Log In'
	| 'Log Out'
	| 'Settings'
	| 'Edit Settings'
	| 'Share on Social Media'
	| 'Copy'
	| 'Cut'
	| 'Paste'
	| 'Undo'
	| 'Redo'
	| 'Zoom In'
	| 'Zoom Out'
	| 'Information'
	| 'Warning'
	| 'Error'
	| 'Success'
	| 'Notification'
	| 'Notification Settings'
	| 'User Profile'
	| 'Privacy'
	| 'Terms and Conditions'
	| 'About Us'
	| 'Contact Us'
	| 'FAQ'
	| 'Help Center'
	| 'Support'
	| 'Feedback'
	| 'Accessibility Settings'
	| 'Dark Mode'
	| 'Light Mode'
	| 'High Contrast Mode'
	| 'Language Settings'
	| 'Date Picker'
	| 'Time Picker'
	| 'Quantity'
	| 'Currency'
	| 'Metric Units'
	| 'Imperial Units'
	| 'Temperature Units'
	| 'Volume Units'
	| 'Weight Units'
	| 'Length Units'
	| 'Area Units'
	| 'Pressure Units'
	| 'Speed Units'
	| 'Angle Units'
	| 'Date Format'
	| 'Time Format'
	| 'Currency Format'
	| 'Password'
	| 'Confirm Password'
	| 'Remember Me'
	| 'Forgot Password'
	| 'New Password'
	| 'Confirm New Password'
	| 'Sign In'
	| 'Sign Up'
	| 'Register'
	| 'Login'
	| 'Continue'
	| 'Skip'
	| 'Terms and Conditions Acceptance'
	| 'Privacy Policy Acceptance';
